import sys

f = 'apps/web/src/pages/DailyReport/DailyAccomplishmentReport.tsx'
lines = open(f, encoding='utf-8').readlines()

new_section = (
'      {/* Section 3: Tasks */}\n'
'      <SectionCard num={3} title="Tasks & Activities" delay={0.3} action={\n'
'        <button type="button" onClick={addRow} className="btn btn-primary">\n'
'          <Plus className="w-4 h-4" /> Add Task Row\n'
'        </button>\n'
'      }>\n'
'        <div className="overflow-x-auto rounded-xl border border-gray-100">\n'
'          <table className="pro-table" style={{ width: "100%", minWidth: "860px" }}>\n'
'            <thead>\n'
'              <tr>\n'
'                {["#","C/O","Priority","Task Type","Ticket / Ref","Task Description","Module","Status","",""].map((h,i) => (\n'
'                  <th key={i} style={{ whiteSpace: "nowrap" }}>{h}</th>\n'
'                ))}\n'
'              </tr>\n'
'            </thead>\n'
'            <tbody>\n'
'              {tasks.map(task => (\n'
'                <React.Fragment key={task.id}>\n'
'                  <tr>\n'
'                    <td className="text-center text-gray-400 font-semibold text-xs" style={{ width: "36px" }}>{task.id}</td>\n'
'                    <td style={{ width: "64px" }}>\n'
'                      <div className="flex flex-col gap-1 items-start">\n'
'                        <label className="flex items-center gap-1 text-xs cursor-pointer">\n'
'                          <input type="checkbox" className="accent-emerald-600 w-3.5 h-3.5" checked={task.carryOver === "Yes"} onChange={() => updateTask(task.id, "carryOver", task.carryOver === "Yes" ? "" : "Yes")} />\n'
'                          <span className="text-gray-600">Yes</span>\n'
'                        </label>\n'
'                        <label className="flex items-center gap-1 text-xs cursor-pointer">\n'
'                          <input type="checkbox" className="accent-rose-500 w-3.5 h-3.5" checked={task.carryOver === "No"} onChange={() => updateTask(task.id, "carryOver", task.carryOver === "No" ? "" : "No")} />\n'
'                          <span className="text-gray-600">No</span>\n'
'                        </label>\n'
'                      </div>\n'
'                    </td>\n'
'                    <td style={{ width: "100px" }}>\n'
'                      <select className="pro-select text-xs py-1 w-full" value={task.priority} onChange={e => updateTask(task.id, "priority", e.target.value)}>\n'
'                        <option value="">--</option><option>High</option><option>Medium</option><option>Low</option>\n'
'                      </select>\n'
'                      {task.priority && (\n'
'                        <span className={`badge mt-1 ${task.priority === "High" ? "badge-danger" : task.priority === "Medium" ? "badge-warning" : "badge-success"}`}>\n'
'                          <span className="badge-dot" />{task.priority}\n'
'                        </span>\n'
'                      )}\n'
'                    </td>\n'
'                    <td style={{ width: "130px" }}>\n'
'                      <select className="pro-select text-xs py-1 w-full" value={task.taskType} onChange={e => updateTask(task.id, "taskType", e.target.value)}>\n'
'                        <option value="">--</option><option>Development</option><option>Bug Fix</option><option>Testing</option><option>Review</option><option>Documentation</option><option>Meeting</option><option>Research</option>\n'
'                      </select>\n'
'                    </td>\n'
'                    <td style={{ width: "100px" }}><input className="pro-input py-1 text-xs w-full" type="text" placeholder="PROJ-101" value={task.ticketRef} onChange={e => updateTask(task.id, "ticketRef", e.target.value)} /></td>\n'
'                    <td style={{ minWidth: "150px" }}><input className="pro-input py-1 text-xs w-full" type="text" placeholder="Describe task..." value={task.description} onChange={e => updateTask(task.id, "description", e.target.value)} /></td>\n'
'                    <td style={{ width: "100px" }}><input className="pro-input py-1 text-xs w-full" type="text" placeholder="Module" value={task.module} onChange={e => updateTask(task.id, "module", e.target.value)} /></td>\n'
'                    <td style={{ width: "120px" }}>\n'
'                      <select className="pro-select text-xs py-1 w-full" value={task.status} onChange={e => updateTask(task.id, "status", e.target.value)}>\n'
'                        <option value="">--</option><option value="done">Done</option><option value="ip">In Progress</option><option value="blocked">Blocked</option><option value="todo">To Do</option>\n'
'                      </select>\n'
'                      {task.status && (\n'
'                        <span className={`badge mt-1 ${statusBadge[task.status]}`}>\n'
'                          <span className="badge-dot" />{statusLabel[task.status]}\n'
'                        </span>\n'
'                      )}\n'
'                    </td>\n'
'                    <td style={{ width: "36px" }} className="text-center">\n'
'                      <button type="button" onClick={() => updateTask(task.id, "_expanded", !task._expanded)}\n'
'                        className="border border-gray-200 rounded px-2 py-1 text-xs text-gray-500 hover:bg-gray-50 transition-all flex items-center gap-1">\n'
'                        <span style={{ display: "inline-block", transform: task._expanded ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>▼</span>\n'
'                      </button>\n'
'                    </td>\n'
'                    <td style={{ width: "36px" }} className="text-center">\n'
'                      <button type="button" onClick={() => deleteRow(task.id)} className="text-rose-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg p-1 transition-all" title="Delete row">\n'
'                        <X className="w-4 h-4" />\n'
'                      </button>\n'
'                    </td>\n'
'                  </tr>\n'
'                  {task._expanded && (\n'
'                    <tr className="bg-gray-50">\n'
'                      <td colSpan={10} className="px-4 py-3">\n'
'                        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">\n'
'                          <div><label className="text-xs text-gray-500 block mb-1">% Done</label><input className="pro-input py-1 text-xs text-center w-full" type="number" min={0} max={100} step={5} placeholder="0" value={task.percentDone} onChange={e => updateTask(task.id, "percentDone", e.target.value)} /></div>\n'
'                          <div><label className="text-xs text-gray-500 block mb-1">Est. Hrs</label><input className="pro-input py-1 text-xs text-center w-full" type="number" min={0} step={0.5} placeholder="0" value={task.estHrs} onChange={e => updateTask(task.id, "estHrs", e.target.value)} /></div>\n'
'                          <div><label className="text-xs text-gray-500 block mb-1">Actual Hrs</label><input className="pro-input py-1 text-xs text-center w-full" type="number" min={0} step={0.5} placeholder="0" value={task.actualHrs} onChange={e => updateTask(task.id, "actualHrs", e.target.value)} /></div>\n'
'                          <div><label className="text-xs text-gray-500 block mb-1">Output / Deliverable</label><input className="pro-input py-1 text-xs w-full" type="text" placeholder="Output description" value={task.output} onChange={e => updateTask(task.id, "output", e.target.value)} /></div>\n'
'                          <div><label className="text-xs text-gray-500 block mb-1">Commit / PR</label><input className="pro-input py-1 text-xs w-full" type="text" placeholder="Commit/PR URL" value={task.commitLink} onChange={e => updateTask(task.id, "commitLink", e.target.value)} /></div>\n'
'                          <div className="col-span-2"><label className="text-xs text-gray-500 block mb-1">Remarks</label><input className="pro-input py-1 text-xs w-full" type="text" placeholder="Remarks" value={task.remarks} onChange={e => updateTask(task.id, "remarks", e.target.value)} /></div>\n'
'                        </div>\n'
'                      </td>\n'
'                    </tr>\n'
'                  )}\n'
'                </React.Fragment>\n'
'              ))}\n'
'            </tbody>\n'
'          </table>\n'
'        </div>\n'
'      </SectionCard>\n'
)

result = lines[:393] + [new_section] + lines[469:]
open(f, "w", encoding="utf-8").writelines(result)
print("Done!")
